version: "3.8"
services:
  go-example:
    container_name: 'go-example'
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - ".:/app"
    command:
      - air